language: python
sudo: false
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
#   PyPy support needs cleanup of doctests, plus some help from zope.security.
#   - TOXENV=pypy
#   - TOXENV=pypy3
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
    email: false
